name: stan
channels:
  - conda-forge
dependencies:
  - arviz=0.11.2
  - numpy=1.21.0
  - matplotlib=3.3.4
  - pip=21.1.3
  - pandas=1.2.5
  - seaborn=0.11.1
  - scipy=1.6.2
  - pip:
    - pystan==3.2.0
